import server from "@guessx/server";

// @ts-ignore Generated by OpenNext and absent in a clean checkout.
import next from "./.open-next/worker.js";

export { GuessRoom } from "@guessx/server";

export default {
  fetch(request, env, context) {
    const pathname = new URL(request.url).pathname;
    if (
      pathname === "/health" ||
      pathname.startsWith("/api/") ||
      pathname.startsWith("/parties/")
    ) {
      return server.fetch(request, env, context);
    }
    return next.fetch(request, env, context);
  },
} satisfies ExportedHandler<CloudflareEnv>;
