import {
  siAdidas,
  siAirbnb,
  siAmericanexpress,
  siApple,
  siAppletv,
  siAudi,
  siBinance,
  siBluesky,
  siBmw,
  siBookingdotcom,
  siBritishairways,
  siBurgerking,
  siCashapp,
  siCisco,
  siCocacola,
  siCoinbase,
  siCrunchyroll,
  siDell,
  siDeliveroo,
  siDiscord,
  siDoordash,
  siEasyjet,
  siEbay,
  siEmirates,
  siEtsy,
  siFacebook,
  siFerrari,
  siFord,
  siGoogle,
  siHandm,
  siHbo,
  siHonda,
  siHp,
  siHyundai,
  siIkea,
  siInstagram,
  siIntel,
  siKfc,
  siKlarna,
  siKlm,
  siLamborghini,
  siLenovo,
  siLg,
  siLufthansa,
  siLyft,
  siMastercard,
  siMastodon,
  siMcdonalds,
  siMonzo,
  siMotorola,
  siNewbalance,
  siNetflix,
  siNissan,
  siNike,
  siNvidia,
  siPaypal,
  siPinterest,
  siPlaystation,
  siPorsche,
  siPuma,
  siQatarairways,
  siRedbull,
  siReddit,
  siRevolut,
  siRyanair,
  siSamsung,
  siShazam,
  siShopify,
  siSnapchat,
  siSony,
  siSoundcloud,
  siSpotify,
  siStarbucks,
  siSteam,
  siStripe,
  siSubaru,
  siSuzuki,
  siTacobell,
  siTarget,
  siTelegram,
  siTesla,
  siTiktok,
  siToyota,
  siTripadvisor,
  siTwitch,
  siUber,
  siUnderarmour,
  siUniqlo,
  siVisa,
  siVimeo,
  siVolkswagen,
  siVolvo,
  siWhatsapp,
  siWise,
  siX,
  siYoutube,
  siZara,
  siZomato,
  type SimpleIcon,
} from "simple-icons";

import { assertTotalRounds, shuffle, type RoundContent } from "./shared";

interface Logo {
  answer: string;
  icon: SimpleIcon;
}

const CATEGORIES: Logo[][] = [
  [
    { answer: "Apple", icon: siApple },
    { answer: "Google", icon: siGoogle },
    { answer: "Samsung", icon: siSamsung },
    { answer: "Sony", icon: siSony },
    { answer: "Intel", icon: siIntel },
    { answer: "NVIDIA", icon: siNvidia },
    { answer: "Dell", icon: siDell },
    { answer: "HP", icon: siHp },
    { answer: "Lenovo", icon: siLenovo },
    { answer: "Cisco", icon: siCisco },
    { answer: "LG", icon: siLg },
    { answer: "Motorola", icon: siMotorola },
  ],
  [
    { answer: "Facebook", icon: siFacebook },
    { answer: "Instagram", icon: siInstagram },
    { answer: "X", icon: siX },
    { answer: "TikTok", icon: siTiktok },
    { answer: "Snapchat", icon: siSnapchat },
    { answer: "Reddit", icon: siReddit },
    { answer: "Pinterest", icon: siPinterest },
    { answer: "WhatsApp", icon: siWhatsapp },
    { answer: "Discord", icon: siDiscord },
    { answer: "Telegram", icon: siTelegram },
    { answer: "Mastodon", icon: siMastodon },
    { answer: "Bluesky", icon: siBluesky },
  ],
  [
    { answer: "Netflix", icon: siNetflix },
    { answer: "Spotify", icon: siSpotify },
    { answer: "YouTube", icon: siYoutube },
    { answer: "Twitch", icon: siTwitch },
    { answer: "Apple TV", icon: siAppletv },
    { answer: "HBO", icon: siHbo },
    { answer: "Shazam", icon: siShazam },
    { answer: "SoundCloud", icon: siSoundcloud },
    { answer: "Vimeo", icon: siVimeo },
    { answer: "Crunchyroll", icon: siCrunchyroll },
    { answer: "Steam", icon: siSteam },
    { answer: "PlayStation", icon: siPlaystation },
  ],
  [
    { answer: "McDonald's", icon: siMcdonalds },
    { answer: "KFC", icon: siKfc },
    { answer: "Starbucks", icon: siStarbucks },
    { answer: "Burger King", icon: siBurgerking },
    { answer: "Coca-Cola", icon: siCocacola },
    { answer: "Taco Bell", icon: siTacobell },
    { answer: "Red Bull", icon: siRedbull },
    { answer: "Deliveroo", icon: siDeliveroo },
    { answer: "DoorDash", icon: siDoordash },
    { answer: "Zomato", icon: siZomato },
  ],
  [
    { answer: "Nike", icon: siNike },
    { answer: "Adidas", icon: siAdidas },
    { answer: "Puma", icon: siPuma },
    { answer: "Zara", icon: siZara },
    { answer: "H&M", icon: siHandm },
    { answer: "Uniqlo", icon: siUniqlo },
    { answer: "IKEA", icon: siIkea },
    { answer: "eBay", icon: siEbay },
    { answer: "Etsy", icon: siEtsy },
    { answer: "Shopify", icon: siShopify },
    { answer: "Target", icon: siTarget },
    { answer: "Under Armour", icon: siUnderarmour },
    { answer: "New Balance", icon: siNewbalance },
  ],
  [
    { answer: "Toyota", icon: siToyota },
    { answer: "Honda", icon: siHonda },
    { answer: "Ford", icon: siFord },
    { answer: "Tesla", icon: siTesla },
    { answer: "BMW", icon: siBmw },
    { answer: "Audi", icon: siAudi },
    { answer: "Volkswagen", icon: siVolkswagen },
    { answer: "Ferrari", icon: siFerrari },
    { answer: "Lamborghini", icon: siLamborghini },
    { answer: "Porsche", icon: siPorsche },
    { answer: "Volvo", icon: siVolvo },
    { answer: "Hyundai", icon: siHyundai },
    { answer: "Subaru", icon: siSubaru },
    { answer: "Suzuki", icon: siSuzuki },
    { answer: "Nissan", icon: siNissan },
  ],
  [
    { answer: "Visa", icon: siVisa },
    { answer: "Mastercard", icon: siMastercard },
    { answer: "PayPal", icon: siPaypal },
    { answer: "Stripe", icon: siStripe },
    { answer: "Revolut", icon: siRevolut },
    { answer: "Wise", icon: siWise },
    { answer: "Cash App", icon: siCashapp },
    { answer: "American Express", icon: siAmericanexpress },
    { answer: "Coinbase", icon: siCoinbase },
    { answer: "Binance", icon: siBinance },
    { answer: "Klarna", icon: siKlarna },
    { answer: "Monzo", icon: siMonzo },
  ],
  [
    { answer: "Airbnb", icon: siAirbnb },
    { answer: "Uber", icon: siUber },
    { answer: "Lyft", icon: siLyft },
    { answer: "Booking.com", icon: siBookingdotcom },
    { answer: "Tripadvisor", icon: siTripadvisor },
    { answer: "Emirates", icon: siEmirates },
    { answer: "British Airways", icon: siBritishairways },
    { answer: "Lufthansa", icon: siLufthansa },
    { answer: "Ryanair", icon: siRyanair },
    { answer: "Qatar Airways", icon: siQatarairways },
    { answer: "KLM", icon: siKlm },
    { answer: "easyJet", icon: siEasyjet },
  ],
];

function svgDataUrl(icon: SimpleIcon): string {
  const color = icon.hex.toUpperCase() === "FFFFFF" ? "111111" : icon.hex;
  // Build from the path so the package's <title> does not reveal the answer.
  const svg = `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="#${color}"><path d="${icon.path}"/></svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

export async function prepareLogoContent(totalRounds: number): Promise<RoundContent[]> {
  const count = assertTotalRounds(totalRounds);
  const candidates = shuffle(
    CATEGORIES.flatMap((logos) => logos.map((logo) => ({ logo, category: logos }))),
  ).slice(0, count);

  return candidates.map(({ logo, category }, index) => ({
    roundNumber: index + 1,
    correctAnswer: logo.answer,
    options: shuffle([
      logo.answer,
      ...shuffle(category.filter((item) => item !== logo))
        .slice(0, 3)
        .map((item) => item.answer),
    ]),
    mediaUrl: svgDataUrl(logo.icon),
    mediaTitle: logo.answer,
    isFinal: index === count - 1,
  }));
}
