import type { RoomMode } from "./models";

export const GAME_MODES: { value: RoomMode; label: string; description: string }[] = [
  { value: "music", label: "Music", description: "Name tracks from artists you pick" },
  { value: "place", label: "Logos", description: "Recognize brands from their marks" },
  { value: "actor", label: "Actors", description: "Put a name to the face" },
  { value: "flag", label: "Flags", description: "Match countries to their flags" },
];

export const ACTOR_CATEGORIES = [
  { code: "nollywood", name: "Nollywood" },
  { code: "hollywood", name: "Hollywood" },
  { code: "bollywood", name: "Bollywood" },
  { code: "kdrama", name: "K-Drama" },
  { code: "british", name: "British Cinema" },
  { code: "french", name: "French Cinema" },
  { code: "anime", name: "Anime" },
  { code: "telenovela", name: "Telenovela" },
] as const;

export type ActorCategory = (typeof ACTOR_CATEGORIES)[number]["code"];

export const CONTINENTS = [
  {
    code: "worldwide",
    name: "Worldwide",
    regions: ["Africa", "Americas", "Asia", "Oceania", "Europe"],
  },
  { code: "africa", name: "Africa", regions: ["Africa"] },
  { code: "americas", name: "Americas", regions: ["Americas"] },
  { code: "asia", name: "Asia-Pacific", regions: ["Asia", "Oceania"] },
  { code: "europe", name: "Europe", regions: ["Europe"] },
] as const;

export type Continent = (typeof CONTINENTS)[number]["code"];

export const POPULAR_ARTISTS: { id: number; name: string }[] = [
  { id: 3933641, name: "Wizkid" },
  { id: 4338602, name: "Burna Boy" },
  { id: 125372, name: "Davido" },
  { id: 51305922, name: "Asake" },
  { id: 5259966, name: "Rema" },
  { id: 2281211, name: "Tiwa Savage" },
  { id: 3744641, name: "Olamide" },
  { id: 903536, name: "CKay" },
  { id: 110616822, name: "Ayra Starr" },
  { id: 13905711, name: "Tems" },
  { id: 15190997, name: "Fireboy DML" },
  { id: 11888005, name: "Joeboy" },
  { id: 56094992, name: "Omah Lay" },
  { id: 66693262, name: "Seyi Vibez" },
  { id: 339760681, name: "FOLA" },
  { id: 61061602, name: "Bella Shmurda" },
  { id: 131904482, name: "Shallipopi" },
  { id: 61550652, name: "Odumodublvck" },
  { id: 50348952, name: "Young Jonn" },
  { id: 8791550, name: "Adekunle Gold" },
  { id: 2965981, name: "Brymo" },
  { id: 10753698, name: "Chike" },
  { id: 14779157, name: "Kizz Daniel" },
  { id: 95330772, name: "Cruel Santino" },
  { id: 12248736, name: "Fave" },
  { id: 161314272, name: "BNXN" },
  { id: 365797, name: "Ruger" },
  { id: 5054583, name: "MaVo" },
  { id: 13293643, name: "Amaarae" },
  { id: 1220981, name: "Tyla" },
  { id: 12096038, name: "Central Cee" },
  { id: 11256100, name: "Dave" },
  { id: 8657430, name: "J Hus" },
  { id: 4723918, name: "Nathaniel Bassey" },
  { id: 1717781, name: "Sinach" },
  { id: 6863915, name: "Mercy Chinwo" },
  { id: 9440, name: "Fela Kuti" },
  { id: 1608773, name: "Yinka Ayefele" },
  { id: 79773, name: "King Sunny Ade" },
  { id: 246791, name: "Drake" },
  { id: 75798, name: "Adele" },
  { id: 4050205, name: "The Weeknd" },
  { id: 12246, name: "Taylor Swift" },
  { id: 384236, name: "Ed Sheeran" },
  { id: 429675, name: "Bruno Mars" },
  { id: 525046, name: "Kendrick Lamar" },
  { id: 9635624, name: "Billie Eilish" },
  { id: 8706544, name: "Dua Lipa" },
];

export const AVATAR_SEEDS = [
  "felix",
  "midnight",
  "zephyr",
  "nova",
  "ember",
  "pixel",
  "glitch",
  "neon",
  "drift",
  "spark",
  "vapor",
  "cipher",
  "echo",
  "prism",
  "volt",
  "ripple",
  "storm",
  "flare",
  "byte",
  "orbit",
  "pulse",
  "shade",
  "blaze",
  "frost",
  "dusk",
  "haze",
  "jade",
  "luna",
  "onyx",
  "reef",
  "sage",
  "thorn",
  "wave",
  "zinc",
  "coral",
  "fern",
  "raven",
  "maple",
  "cosmo",
  "indigo",
  "pepper",
  "willow",
  "atlas",
  "brisk",
  "cleo",
  "delta",
  "flint",
  "glow",
  "hawk",
  "iris",
  "jolt",
  "karma",
  "lark",
  "moss",
  "opal",
  "quake",
  "rust",
  "silk",
  "tide",
  "umber",
  "vex",
  "wren",
  "xenon",
  "yeti",
  "zeal",
  "amber",
] as const;

export function getAvatarUrl(seed: string, format: "png" | "svg" = "png"): string {
  return `https://api.dicebear.com/9.x/adventurer/${format}?seed=${encodeURIComponent(seed)}`;
}
